---
server:
  port: ${PORT}

spring:
  config:
    import: file:.env[.properties]
  application:
    name: book-library-api-practice
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  liquibase:
    change-log: "classpath:/db/changelog/changelog.yml"

book-library:
  jwt:
    access:
      secret: ${ACCESS_TOKEN_SECRET}
      expiration: ${ACCESS_TOKEN_EXPIRATION_IN_MILLIS}
    refresh:
      secret: ${REFRESH_TOKEN_SECRET}
      expiration: ${REFRESH_TOKEN_EXPIRATION_IN_MILLIS}