---
server:
  port: ${PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: book-library-api-practice
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
